### ISSUE TITLE
 Error: While importing "app", an ImportError was raised:

### ISSUE THREAD

**Issue by thygesteffensen** [rehandalal/flask-mobility#13]
Hello there,

I cannot find any issue similar to this, so here I am seeking help.

First up, this is pretty sweet if I can get it to work, nice job!

However, I followed your guide to setup flask-mobility, but I got an error.
This was the error I got, by following your example [here.](https://flask-mobility.readthedocs.io/en/latest/#id11)

I installed flask-mobility be adding this, 'flask-mobility' , to my requirements file and then installed that.

Error message:

> FLASK_APP = app.py
> FLASK_ENV = development
> FLASK_DEBUG = 0
> In folder C:/Users/Thyge Steffensen/PycharmProjects/untitled
> "C:\Users\Thyge Steffensen\PycharmProjects\untitled\venv\Scripts\python.exe" -m flask run
>  * Serving Flask app "app.py"
>  * Environment: development
>  * Debug mode: off
> Usage: python -m flask run [OPTIONS]
> 
> Error: While importing "app", an ImportError was raised:
> 
> Traceback (most recent call last):
>   File "C:\Users\Thyge Steffensen\PycharmProjects\untitled\venv\lib\site-packages\flask\cli.py", line 235, in locate_app
>    __import__(module_name)
>   File "C:\Users\Thyge Steffensen\PycharmProjects\untitled\app.py", line 17, in <module>
>    from flask.ext.mobility import Mobility
> ModuleNotFoundError: No module named 'flask.ext'
>
>
> Process finished with exit code 2

**Comment by rehandalal** [comment]
It appears that flask has deprecated the `flask.ext` syntax. Can you try:
```py
from flask_mobility import Mobility
```

**Comment by thygesteffensen** [comment]
Yes, great! That works, thank you!
